### ISSUE TITLE
Azure DevOps CI/CD Pipeline for SSRS PowerShellScript repository?

### ISSUE THREAD

**Issue by PokeyTheCat** [AnupKumarMishra86/about_me#1]
I've noticed your `PowerShellScript ` repository is not public or has been removed. I was wondering if you still have access to it and have the file. `PowerShellScript/blob/master/TFS/SSRSCICD.ps1`.

I've found you from your really nice blogpost on [Azure DevOps CI/CD Pipeline for SSRS](https://www.studydevops.in/2019/03/azure-devops-cicd-pipeline-for-ssrs.html).

Thanks!

**Comment by oishiimendesu** [comment]
https://www.studydevops.in/2019/03/azure-devops-cicd-pipeline-for-ssrs.html

Same here! 🤗

**Comment by oishiimendesu** [comment]
> I've noticed your `PowerShellScript ` repository is not public or has been removed. I was wondering if you still have access to it and have the file. `PowerShellScript/blob/master/TFS/SSRSCICD.ps1`.
> 
> I've found you from your really nice blogpost on [Azure DevOps CI/CD Pipeline for SSRS](https://www.studydevops.in/2019/03/azure-devops-cicd-pipeline-for-ssrs.html).
> 
> Thanks!

https://www.studydevops.in/2019/03/azure-devops-cicd-pipeline-for-ssrs.html

Same here! 🤗

@PokeyTheCat have you got it? Can you share it? @PokeyTheCat  @AnupDevOps
